default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  port: 3308
  socket: /tmp/mysql.sock
  database: shinq_sample_development

test:
  <<: *default
  port: 3308
  socket: /tmp/mysql.sock
  database: shinq_sample_test

production:
  <<: *default
  database: shinq_sample

